application: test
version: 1
runtime: python
api_version: 1

handlers:

- url: /(favicon\.ico)
  static_files: _static/\1
  upload: _static/(.*)
  
- url: /_static
  static_dir: _static
  
- url: .*
  script: hypernodes.py
